### ISSUE TITLE
Fatal Error when cookie samesite is null

### ISSUE THREAD

**Issue by superdav42** [chubbyphp/chubbyphp-swoole-request-handler#3]
I ran into the following error when trying to emit a response with a cookie that had no samesite attribute set. 
Fatal error: Uncaught TypeError: Swoole\Http\Response::cookie(): Argument #8 ($samesite) must be of type string, null given in /vendor/chubbyphp/chubbyphp-swoole-request-handler/src/SwooleResponseEmitter.php:41

This is with PHP 8.0 and Swoole 4.6.0. 
It's pretty easy to work around this bug by ensuring all cookies have a Lax samesite but it's not ideal.
I believe the proper fix is to send the empty string instead of null. So make this change to the SwooleResponseEmitter class
```php
    private function mapSameSite(SetCookie $cookie): ?string
    {
        if (null === $sameSite = $cookie->getSameSite()) {
            return '';
        }

        return str_replace('SameSite=', '', $sameSite->asString());
    }
```
Then cookies are sent without error and they do not have samesite attribute at all.

**Comment by dominikzogg** [comment]
@superdav42 thanks to submitting this issue. To me it looks like an issue of swoole or at least a bug in there ide helper, cause there null is allowed: https://github.com/swoole/ide-helper/blob/master/output/swoole/namespace/Http/Response.php#L35

**Comment by dominikzogg** [comment]
@superdav42 FYI: https://github.com/swoole/swoole-src/issues/4077

**Comment by sy-records** [comment]
> @superdav42 thanks to submitting this issue. To me it looks like an issue of swoole or at least a bug in there ide helper, cause there null is allowed: https://github.com/swoole/ide-helper/blob/master/output/swoole/namespace/Http/Response.php#L35

swoole/ide-helper No TypeHinting https://github.com/swoole/ide-helper/issues/19

**Comment by sy-records** [comment]
see https://www.swoole.co.uk/docs/modules/swoole-http-response-cookie

can be set to an empty string instead of null

**Comment by dominikzogg** [comment]
@superdav42 https://github.com/chubbyphp/chubbyphp-swoole-request-handler/actions/runs/620057364
