### ISSUE TITLE
You have set 'Transfer-Encoding', 'Content-Length' will be ignored

### ISSUE THREAD

**Issue by duxphp** [chubbyphp/chubbyphp-swoole-request-handler#6]
private function mapBody(ResponseInterface $response, SwooleResponse $swooleResponse): void
    {
        $body = $response->getBody();

        if ($body->isSeekable()) {
            $body->rewind();
        }

        while (!$body->eof()) {
            if ('' !== $chunk = $body->read(256)) {
                $swooleResponse->write($chunk);
            }
        }
    }
    
    
    
The following error occurs when exporting a static file:

```
You have set 'Transfer-Encoding', 'Content-Length' will be ignored 
```

**Comment by dominikzogg** [comment]
Hi @duxphp 

Thanks for submitting this error. Can you provide me a stack trace of more information about which code get called when, and especially which code throws the error?

Best,
Dominik

**Comment by duxphp** [comment]
Resolved by swoole external interception
